 version: '2'
 services:

   db:
     image: postgres

   initdb:
     build: .
     command: python manage.py makemigrations
     depends_on:
       - db
       
   datamigration:
     build: .
     command: python manage.py migrate
     depends_on:
       - initdb
     


   web:
     build: .
     command: python manage.py runsslserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
       - db