# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 08:14
from __future__ import unicode_literals

from django.db import migrations

from django.utils import timezone

def insert_fake_news_site_data(apps, schema_editor):
    FakeSite = apps.get_model("hapifakenews", "FakeSite")

    site = FakeSite(name = '',
                    url = '',
                    sourcename = '',
                    sourceUrl = '',
                    created = timezone.now(), createdby = 0, updated = timezone.now())
    site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0007_auto_20161129_1649'),
    ]

    operations = [
    ]
