# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=1)),
                ('sourceurl', models.CharField(max_length=255)),
                ('sourcename', models.CharField(max_length=255)),
                ('ratingatsource', models.CharField(max_length=64)),
                ('comment', models.CharField(max_length=512)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdby', models.IntegerField(default=1)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
