# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 07:15
from __future__ import unicode_literals

from django.db import migrations

from django.utils import timezone
import datetime

def insert_fake_news_site_data(apps, schema_editor):
    FakeSite = apps.get_model("hapifakenews", "FakeSite")

    site = FakeSite(url = 'http://100percentfedup.com/', name = '100PercentFedUp.com', ratingatsource = '2, 3', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()
    
    site = FakeSite(url = 'http://enduringvision.com/', name = 'EnduringVision.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()
        
    site = FakeSite(url = 'http://21stcenturywire.com/', name = '21stCenturyWire.com', ratingatsource = '2, 3', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'https://70news.wordpress.com/', name = '70news.wordpress.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()
    
    site = FakeSite(url = 'http://www.abcnews.com.co/', name = 'Abcnews.com.co', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://activistpost.com/', name = 'ActivistPost.com', ratingatsource = '2, 3', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://www.americannews.com/', name = 'AmericanNews.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://realnewsrightnow.com/', name = 'RealNewsRightNow.com', ratingatsource = '1, 4', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://infowars.com/', name = 'Infowars.com', ratingatsource = '1, 2', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://bluenationreview.com/', name = 'Blue Nation Review', ratingatsource = '2,3', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://www.breitbart.com/', name = 'Breitbart', ratingatsource = '2, 3', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://rilenews.com/', name = 'RileNews.com', ratingatsource = '1, 4', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://civictribune.com/', name = 'CivicTribune.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://coasttocoastam.com/', name = 'CoastToCoastAM.com', ratingatsource = '2', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://mediamass.net/', name = 'MediaMass.net', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://consciouslifenews.com/', name = 'ConsciousLifeNews.com', ratingatsource = '2', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()


    site = FakeSite(url = 'http://countdowntozerotime.com/', name = 'CountdownToZeroTime.com', ratingatsource = '2', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://nationalreport.net/', name = 'NationalReport.net', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://creambmp.com/', name = 'CreamBMP.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://naturalnews.com/', name = 'NaturalNews.com', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://news-hound.com/', name = 'News-Hound.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://newsbiscuit.com', name = 'NewsBiscuit.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://dcgazette.com/', name = 'DCGazette.com', ratingatsource = '1', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()

    site = FakeSite(url = 'http://newsmutiny.com/', name = 'NewsMutiny.com', ratingatsource = '1, 4', sourcename = 'Melissa Zimdars / DailyDot', comment='Sites where category >= 2 and URL available', sourceurl = 'http://www.dailydot.com/layer8/fake-news-sites-list-facebook/', created = datetime.datetime(2016, 12, 3, 10, 47), createdby = 0, updated = datetime.datetime(2016, 12, 3, 10, 47))
    site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_fake_news_site_data),
    ]
