# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0005_auto_20161126_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FakeNews',
        ),
        migrations.DeleteModel(
            name='SentimentData',
        ),
        migrations.AddField(
            model_name='fakesite',
            name='createdby',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fakesite',
            name='since',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
