# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0006_auto_20161129_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakesite',
            old_name='since',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='fakesite',
            name='type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fakesite',
            name='url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
