# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0007_auto_20161129_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakesite',
            old_name='site',
            new_name='name',
        ),
        migrations.AddField(
            model_name='fakesite',
            name='ratingfromsource',
            field=models.CharField(default='', max_length=64),
        ),
    ]
