# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 09:34
from __future__ import unicode_literals

from django.db import migrations
from django.utils import timezone



class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0008_auto_20161203_0934'),
    ]

    operations = [
    ]
