# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0002_auto_20161206_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakesite',
            old_name='comment',
            new_name='comment_from_api',
        ),
        migrations.RenameField(
            model_name='fakesite',
            old_name='ratingatsource',
            new_name='source_extra_info',
        ),
        migrations.RenameField(
            model_name='fakesite',
            old_name='sourcename',
            new_name='source_name',
        ),
        migrations.RenameField(
            model_name='fakesite',
            old_name='sourceurl',
            new_name='source_url',
        ),
    ]
