# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hapifakenews', '0004_auto_20161206_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakesite',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
